#include "GEpch.h"
#include "Platform/D3D12/D3D12StorageImage2D.h"
#include "Platform/D3D12/D3D12Context.h"
#include "Platform/D3D12/D3D12Utils.h"

namespace GEngine
{
	static DXGI_FORMAT ToDxgiFormat(ComputeImage2DFormat format)
	{
		switch (format)
		{
		case COMPUTE_IMAGE_2D_FORMAT_RGBA32_SFLOAT: return DXGI_FORMAT_R32G32B32A32_FLOAT;
		case COMPUTE_IMAGE_2D_FORMAT_RGBA16_SFLOAT: return DXGI_FORMAT_R16G16B16A16_FLOAT;
		case COMPUTE_IMAGE_2D_FORMAT_RG32_SFLOAT: return DXGI_FORMAT_R32G32_FLOAT;
		case COMPUTE_IMAGE_2D_FORMAT_RG16_SFLOAT: return DXGI_FORMAT_R16G16_FLOAT;
		case COMPUTE_IMAGE_2D_FORMAT_R32_SFLOAT: return DXGI_FORMAT_R32_FLOAT;
		case COMPUTE_IMAGE_2D_FORMAT_R16_SFLOAT: return DXGI_FORMAT_R16_FLOAT;
		case COMPUTE_IMAGE_2D_FORMAT_RGBA32_SINT: return DXGI_FORMAT_R32G32B32A32_SINT;
		case COMPUTE_IMAGE_2D_FORMAT_RGBA16_SINT: return DXGI_FORMAT_R16G16B16A16_SINT;
		case COMPUTE_IMAGE_2D_FORMAT_RGBA8_SINT: return DXGI_FORMAT_R8G8B8A8_SINT;
		case COMPUTE_IMAGE_2D_FORMAT_RGBA32_UINT: return DXGI_FORMAT_R32G32B32A32_UINT;
		case COMPUTE_IMAGE_2D_FORMAT_RGBA16_UINT: return DXGI_FORMAT_R16G16B16A16_UINT;
		case COMPUTE_IMAGE_2D_FORMAT_RGBA8_UINT: return DXGI_FORMAT_R8G8B8A8_UINT;
		case COMPUTE_IMAGE_2D_FORMAT_R32_UINT: return DXGI_FORMAT_R32_UINT;
		default: GE_CORE_ASSERT(false, "Unsupported D3D12 storage-image format."); return DXGI_FORMAT_UNKNOWN;
		}
	}

	D3D12StorageImage2D::D3D12StorageImage2D(uint32_t width, uint32_t height, ComputeImage2DFormat format)
	{
		const DXGI_FORMAT dxgiFormat = ToDxgiFormat(format);
		D3D12_RESOURCE_DESC desc = CD3DX12_RESOURCE_DESC::Tex2D(dxgiFormat, width, height, 1, 1, 1, 0, D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS);
		D3D12_THROW_IF_FAILED(D3D12Context::Get()->GetDevice()->CreateCommittedResource(
			&CD3DX12_HEAP_PROPERTIES(D3D12_HEAP_TYPE_DEFAULT), D3D12_HEAP_FLAG_NONE, &desc,
			D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr, IID_PPV_ARGS(&m_Resource)));

		m_UavDesc.Format = dxgiFormat;
		m_UavDesc.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
		m_UavDesc.Texture2D.MipSlice = 0;
		m_UavDesc.Texture2D.PlaneSlice = 0;
	}
}
