#pragma once
#include "GEngine/Core/Core.h"

namespace GEngine
{
	enum RenderImage2DFormat
	{
		RENDER_IMAGE_2D_FORMAT_NONE,
		RENDER_IMAGE_2D_FORMAT_RGBA8F,
		RENDER_IMAGE_2D_FORMAT_RGB8F,
	};

	static uint32_t RenderImage2DFormatChannelSize(RenderImage2DFormat format)
	{
		switch (format)
		{
		case RENDER_IMAGE_2D_FORMAT_NONE:		return 0;
		case RENDER_IMAGE_2D_FORMAT_RGBA8F:		return 4;
		case RENDER_IMAGE_2D_FORMAT_RGB8F:		return 3;
		default:
			break;
		}
	}

	enum ComputeImage2DFormat
	{
		COMPUTE_IMAGE_2D_FORMAT_NONE,
		COMPUTE_IMAGE_2D_FORMAT_RGBA32F,
		COMPUTE_IMAGE_2D_FORMAT_RGBA16F,
		COMPUTE_IMAGE_2D_FORMAT_RG32F,
		COMPUTE_IMAGE_2D_FORMAT_RG16F,
		COMPUTE_IMAGE_2D_FORMAT_R32F,
		COMPUTE_IMAGE_2D_FORMAT_R16F,
		COMPUTE_IMAGE_2D_FORMAT_RGBA32I,
		COMPUTE_IMAGE_2D_FORMAT_RGBA16I,
		COMPUTE_IMAGE_2D_FORMAT_RGBA8I,
		COMPUTE_IMAGE_2D_FORMAT_RGBA32UI,
		COMPUTE_IMAGE_2D_FORMAT_RGBA16UI,
		COMPUTE_IMAGE_2D_FORMAT_RGBA8UI,
		COMPUTE_IMAGE_2D_FORMAT_R32UI
	};
}